[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[etherscan]
celo-alfajores = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api"}
celo = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api"}
dango = { key = "${CELOSCAN_API_KEY}", url = " https://celo-dango.blockscout.com/api"}

[rpc_endpoints]
celo-alfajores = "https://alfajores-forno.celo-testnet.org"
celo = "https://forno.celo.org"
dango = " https://forno.dango.celo-testnet.org/"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options



# forge create src/AutoSafe.sol:AutoSafe --rpc-url https://alfajores-forno.celo-testnet.org --private-key 